---
- hosts: all
  tasks: 
  - name: Apt get update
    apt: update_cache=yes
    become: true
    when: ansible_os_family == 'Debian'
    
  - name: yum update
    command: yum makecache
    become: true   
    when: ansible_os_family == 'RedHat' 
    
  - name: Install iostat, monit
    apt: name={{ item }} state=present
    with_items:
    - monit
    - sysstat
    become: true
    when: ansible_os_family == 'Debian'
    
  - name: Install iostat, monit
    yum: name={{ item }} state=present
    with_items:
    - monit
    - sysstat
    become: true
    when: ansible_os_family == 'RedHat'    
    
  - name: copying monit config file from local machine to remote machine
    copy: src=monitrc dest=/etc/monit/monitrc
    notify: Start the monit service
    become: true
    
  handlers:
  - name: Start the monit service
    service: name=monit state=started
    become: true
